### ISSUE TITLE
Package not installable

### ISSUE THREAD

**Issue by dferber90** [preconstruct/a-random-number#6]
*First of all, thanks for making `preconstruct`. It elegantly solves such a huge pain point :)*

Installing this package with yarn (and possibly with npm) is not working, unless I'm missing something.

```
yarn add a-random-number
```

in any project leads to

```
error /Users/xxx/project/node_modules/a-random-number: Command failed.
Exit code: 127
Command: preconstruct dev
Arguments:




```

The reason seems to be this line

https://github.com/preconstruct/a-random-number/blob/a5a61d8ce01b5e2b185c242a0921eca3b3c5b94f/package.json#L14

I tried using this example package and building a package based on it. But that package has the same problem.

Could it be that this line is only there for the example package and not meant to be included in a real package?

**Comment by emmatown** [comment]
Whoops, that shouldn't be there at all for non-monorepos. thanks for catching it!
